# Generated by Django 3.2.6 on 2021-08-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_ajax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_ajax',
            name='image',
            field=models.ImageField(upload_to='products_ajax'),
        ),
    ]
