# Generated by Django 3.2.6 on 2021-08-10 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
