# Generated by Django 3.2.6 on 2021-08-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_products_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
