# Generated by Django 3.2.6 on 2021-08-10 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
